### ISSUE TITLE
Unable to access parts of the site

### ISSUE THREAD

**Issue by kelsiegosser** [freeCodeCamp/support#3]
When trying to visit various parts of the freecodecamp site, I frequently run into this issue which lasts typically for minutes but sometimes longer:

![image](https://user-images.githubusercontent.com/23170565/62071095-c8832b00-b209-11e9-9208-9d142666917d.png)

I cannot view the support site as of now either:

![image](https://user-images.githubusercontent.com/23170565/62071119-d5a01a00-b209-11e9-8661-0123615a363e.png)

Additionally, when this is happening, my curriculum page does not update to reflect the lessons I have completed. I have to re-enter those lessons and press submit again.

I am using Chrome.

_Apologies if this is the improper place to report this issue._

**Comment by raisedadead** [comment]
Please reachout to our [community forum](https://www.freecodecamp.org/forum)
